[package]
name = "statiker"
version = "0.1.0"
edition = "2021"
description = "Serves static files from a directory"
authors = ["Patrick Arndt <patrick.arndt.99@web.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features=["cargo"]}
