name: Build and release statiker
on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          # - build: macos | # NOPE I DONT DO THIS. YOU'RE RICH ENOUGH TO DO IT YOURSELF.
          #   os: macos-latest
          #   target: x86_64-apple-darwin

          - build: windows-gnu
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Add this line to checkout submodules

      # Get version from cargo.toml
      - name: Get version
        id: get_version
        run: echo "VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}

      - name: Install mingw-w64
        if: matrix.build == 'windows-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 zip

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target ${{ matrix.target }} 

      - name: Build archive
        shell: bash
        run: |
          binary_name="statiker"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.build}}" = "windows-gnu" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname/$binary_name.exe"
            echo "ASSET=$dirname/$binary_name.exe" >> $GITHUB_ENV
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname/$binary_name"
            echo "ASSET=$dirname/$binary_name" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: matrix.build == 'linux'
        uses: docker/setup-buildx-action@v3


      - name: Login Docker Hub
        if: matrix.build == 'linux'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        if: matrix.build == 'linux'
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/statiker:${{ env.VERSION }},docker.io/${{ secrets.DOCKERHUB_USERNAME }}/statiker:latest

          
      - name: Tag commit
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
          tag_name: ${{ env.VERSION }}
